service: nodeless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  memorySize: 256
  iamRoleStatements: 
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::*" #acesso a todos os buckets do s3
  lambdaHashingVersion: 20201221

functions:
  optimize:
    handler: optimize.handle
    environment: 
      bucket: serverlessbucketoptimizeimage
    events:
      - s3:
          bucket: serverlessbucketoptimizeimage
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg
      - s3:
          bucket: serverlessbucketoptimizeimage
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .png